localeChangers:
  alphaROMdiE:
    enable: false
    exec: 'C:\Resources\Games\AlphaROMdiE.exe %GAME_PATH%'
    name: AlphaROMdiE
  localeEmulator:
    enable: true
    exec: 'D:\Game\Gal\Tools\Locale.Emulator\LEProc.exe %GAME_PATH%'
    name: Locale Emulator
  noChanger:
    enable: false
    exec: '%GAME_PATH%'
    name: No Changer
  ntleas:
    enable: false
    exec: 'C:\ntleas046_x64\x86\ntleas.exe %GAME_PATH%'
    name: Ntleas
onlineApis:
  - enable: false
    external: true
    jsFile: config\qqApi.js
    name: 腾讯
  - enable: false
    external: true
    jsFile: config\tencentApi.js
    name: 腾讯云
  - enable: false
    external: true
    jsFile: config\youdaoApi.js
    name: 有道
  - enable: false
    method: POST
    name: 谷歌
    requestBodyFormat: 'X{"q": %TEXT%, "sl": "ja", "tl": "zh-CN"}'
    responseBodyPattern: 'Rclass="t0">([^<]*)<'
    url: 'https://translate.google.cn/m'
  - enable: true
    external: true
    jsFile: config\caiyunApi.js
    name: 彩云
  - enable: false
    external: true
    jsFile: config\azureApi.js
    name: Azure
  - enable: true
    external: true
    jsFile: config\baiduApi.js
    name: 百度
  - enable: false
    external: true
    jsFile: config\newBaiduApi.js
    name: 百度开放平台
translators:
  jBeijing:
    dictPath: 'D:\Code\YUKI-Translator\lib\dict\jb'
    enable: true
    path: 'D:\Game\Gal\Tools\JBeijing7'
dictionaries:
  lingoes:
    enable: false
    path: 'C:\YUKI\libraries\dict\lingoes\njcd.db'
mecab:
  enable: true
  path: 'D:\Game\Gal\Tools\mecab-ipadic'
librariesRepoUrl: 'https://github.com/project-yuki/libraries/raw/master/_pack/'
language: zh
